# Generated by Django 2.2.24 on 2021-07-27 11:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KlantNotificatie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Unieke resource identifier (UUID4)', unique=True)),
                ('klant', models.URLField(help_text='URL-referentie naar de KLANT (in de Klanten API)', max_length=1000, verbose_name='klant')),
                ('productaanvraag', models.URLField(help_text='URL-referentie naar de ProductAanvraag (in de Objecten API) van de KLANT', max_length=1000, verbose_name='productaanvraag')),
                ('bericht', models.TextField(help_text='Het bericht voor de klant', verbose_name='bericht')),
            ],
            options={
                'verbose_name': 'klantnotificatie',
                'verbose_name_plural': 'klantnotificaties',
            },
        ),
    ]
