openapi: 3.0.0
info:
  title: Klantnotificaties API
  description: 'Een API om een Klantnotificaties aan te maken.


    Deze API kan aangeroepen worden door andere systemen, om bijvoorbeeld emails naar

    klanten te versturen.


    **Autorisatie**


    Deze API vereist autorisatie. Je kan de

    [token-tool](https://ref.tst.vng.cloud/tokens/) gebruiken om JWT-tokens te

    genereren.


    **Handige links**


    * [Aan de slag](https://ref.tst.vng.cloud/ontwikkelaars/)

    * ["Papieren" standaard](https://ref.tst.vng.cloud/standaard/)

    '
  contact:
    url: https://github.com/VNG-Realisatie/gemma-zaken
    email: support@maykinmedia.nl
  license:
    name: EUPL 1.2
  version: 1.0.0-rc1
security:
- JWT-Claims: []
paths:
  /klantnotificaties:
    get:
      operationId: klantnotificatie_list
      summary: Alle KLANTNOTIFICATIEs opvragen.
      description: Alle KLANTNOTIFICATIEs opvragen.
      responses:
        '200':
          description: OK
          headers:
            API-version:
              schema:
                type: string
              description: 'Geeft een specifieke API-versie aan in de context van
                een specifieke aanroep. Voorbeeld: 1.2.1.'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/KlantNotificatie'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '406':
          $ref: '#/components/responses/406'
        '409':
          $ref: '#/components/responses/409'
        '410':
          $ref: '#/components/responses/410'
        '415':
          $ref: '#/components/responses/415'
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'
      tags:
      - klantnotificaties
    post:
      operationId: klantnotificatie_create
      summary: Maak een KLANTNOTIFICATIE aan.
      description: Maak een KLANTNOTIFICATIE aan.
      parameters:
      - name: Content-Type
        in: header
        description: Content type van de verzoekinhoud.
        required: true
        schema:
          type: string
          enum:
          - application/json
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/KlantNotificatie'
        required: true
      responses:
        '201':
          description: Created
          headers:
            API-version:
              schema:
                type: string
              description: 'Geeft een specifieke API-versie aan in de context van
                een specifieke aanroep. Voorbeeld: 1.2.1.'
            Location:
              schema:
                type: string
                format: uri
              description: URL waar de resource leeft.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KlantNotificatie'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '406':
          $ref: '#/components/responses/406'
        '409':
          $ref: '#/components/responses/409'
        '410':
          $ref: '#/components/responses/410'
        '415':
          $ref: '#/components/responses/415'
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'
      tags:
      - klantnotificaties
    parameters: []
  /klantnotificaties/{uuid}:
    get:
      operationId: klantnotificatie_read
      summary: Een specifieke KLANTNOTIFICATIE opvragen.
      description: Een specifieke KLANTNOTIFICATIE opvragen.
      parameters:
      - name: If-None-Match
        in: header
        description: "Voer een voorwaardelijk verzoek uit. Deze header moet \xE9\xE9\
          n of meerdere ETag-waardes bevatten van resources die de consumer gecached\
          \ heeft. Indien de waarde van de ETag van de huidige resource voorkomt in\
          \ deze set, dan antwoordt de provider met een lege HTTP 304 request. Zie\
          \ [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-None-Match)\
          \ voor meer informatie."
        required: false
        examples:
          oneValue:
            summary: "E\xE9n ETag-waarde"
            value: '"79054025255fb1a26e4bc422aef54eb4"'
          multipleValues:
            summary: Meerdere ETag-waardes
            value: '"79054025255fb1a26e4bc422aef54eb4", "e4d909c290d0fb1ca068ffaddf22cbd0"'
        schema:
          type: string
      responses:
        '200':
          description: OK
          headers:
            ETag:
              description: De ETag berekend op de response body JSON. Indien twee
                resources exact dezelfde ETag hebben, dan zijn deze resources identiek
                aan elkaar. Je kan de ETag gebruiken om caching te implementeren.
              schema:
                type: string
            API-version:
              schema:
                type: string
              description: 'Geeft een specifieke API-versie aan in de context van
                een specifieke aanroep. Voorbeeld: 1.2.1.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KlantNotificatie'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '406':
          $ref: '#/components/responses/406'
        '409':
          $ref: '#/components/responses/409'
        '410':
          $ref: '#/components/responses/410'
        '415':
          $ref: '#/components/responses/415'
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'
      tags:
      - klantnotificaties
    parameters:
    - name: uuid
      in: path
      description: Unieke resource identifier (UUID4)
      required: true
      schema:
        type: string
        format: uuid
tags:
- name: klantnotificaties
  description: ''
servers:
- url: /api/v1
components:
  responses:
    '400':
      description: Bad request
      headers:
        API-version:
          schema:
            type: string
          description: 'Geeft een specifieke API-versie aan in de context van een
            specifieke aanroep. Voorbeeld: 1.2.1.'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ValidatieFout'
    '401':
      description: Unauthorized
      headers:
        API-version:
          schema:
            type: string
          description: 'Geeft een specifieke API-versie aan in de context van een
            specifieke aanroep. Voorbeeld: 1.2.1.'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Fout'
    '403':
      description: Forbidden
      headers:
        API-version:
          schema:
            type: string
          description: 'Geeft een specifieke API-versie aan in de context van een
            specifieke aanroep. Voorbeeld: 1.2.1.'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Fout'
    '404':
      description: Not found
      headers:
        API-version:
          schema:
            type: string
          description: 'Geeft een specifieke API-versie aan in de context van een
            specifieke aanroep. Voorbeeld: 1.2.1.'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Fout'
    '406':
      description: Not acceptable
      headers:
        API-version:
          schema:
            type: string
          description: 'Geeft een specifieke API-versie aan in de context van een
            specifieke aanroep. Voorbeeld: 1.2.1.'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Fout'
    '409':
      description: Conflict
      headers:
        API-version:
          schema:
            type: string
          description: 'Geeft een specifieke API-versie aan in de context van een
            specifieke aanroep. Voorbeeld: 1.2.1.'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Fout'
    '410':
      description: Gone
      headers:
        API-version:
          schema:
            type: string
          description: 'Geeft een specifieke API-versie aan in de context van een
            specifieke aanroep. Voorbeeld: 1.2.1.'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Fout'
    '412':
      description: Precondition failed
      headers:
        API-version:
          schema:
            type: string
          description: 'Geeft een specifieke API-versie aan in de context van een
            specifieke aanroep. Voorbeeld: 1.2.1.'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Fout'
    '415':
      description: Unsupported media type
      headers:
        API-version:
          schema:
            type: string
          description: 'Geeft een specifieke API-versie aan in de context van een
            specifieke aanroep. Voorbeeld: 1.2.1.'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Fout'
    '429':
      description: Too many requests
      headers:
        API-version:
          schema:
            type: string
          description: 'Geeft een specifieke API-versie aan in de context van een
            specifieke aanroep. Voorbeeld: 1.2.1.'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Fout'
    '500':
      description: Internal server error
      headers:
        API-version:
          schema:
            type: string
          description: 'Geeft een specifieke API-versie aan in de context van een
            specifieke aanroep. Voorbeeld: 1.2.1.'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Fout'
  securitySchemes:
    JWT-Claims:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    KlantNotificatie:
      required:
      - klant
      - productaanvraag
      - bericht
      - kanaal
      type: object
      properties:
        url:
          title: Url
          description: URL-referentie naar dit object. Dit is de unieke identificatie
            en locatie van dit object.
          type: string
          format: uri
          readOnly: true
          maxLength: 1000
          minLength: 1
        klant:
          title: Klant
          description: URL-referentie naar de KLANT (in de Klanten API)
          type: string
          format: uri
          maxLength: 1000
          minLength: 1
        productaanvraag:
          title: Productaanvraag
          description: URL-referentie naar de ProductAanvraag (in de Objecten API)
            van de KLANT
          type: string
          format: uri
          maxLength: 1000
          minLength: 1
        bericht:
          title: Bericht
          description: Het bericht voor de klant
          type: string
          minLength: 1
        kanaal:
          title: Kanaal
          description: Het kanaal waarlangs het bericht naar de klant gestuurd moet
            worden
          type: string
          enum:
          - email
          - sms
    Fout:
      required:
      - code
      - title
      - status
      - detail
      - instance
      type: object
      properties:
        type:
          title: Type
          description: URI referentie naar het type fout, bedoeld voor developers
          type: string
        code:
          title: Code
          description: Systeemcode die het type fout aangeeft
          type: string
          minLength: 1
        title:
          title: Title
          description: Generieke titel voor het type fout
          type: string
          minLength: 1
        status:
          title: Status
          description: De HTTP status code
          type: integer
        detail:
          title: Detail
          description: Extra informatie bij de fout, indien beschikbaar
          type: string
          minLength: 1
        instance:
          title: Instance
          description: URI met referentie naar dit specifiek voorkomen van de fout.
            Deze kan gebruikt worden in combinatie met server logs, bijvoorbeeld.
          type: string
          minLength: 1
    FieldValidationError:
      required:
      - name
      - code
      - reason
      type: object
      properties:
        name:
          title: Name
          description: Naam van het veld met ongeldige gegevens
          type: string
          minLength: 1
        code:
          title: Code
          description: Systeemcode die het type fout aangeeft
          type: string
          minLength: 1
        reason:
          title: Reason
          description: Uitleg wat er precies fout is met de gegevens
          type: string
          minLength: 1
    ValidatieFout:
      required:
      - code
      - title
      - status
      - detail
      - instance
      - invalidParams
      type: object
      properties:
        type:
          title: Type
          description: URI referentie naar het type fout, bedoeld voor developers
          type: string
        code:
          title: Code
          description: Systeemcode die het type fout aangeeft
          type: string
          minLength: 1
        title:
          title: Title
          description: Generieke titel voor het type fout
          type: string
          minLength: 1
        status:
          title: Status
          description: De HTTP status code
          type: integer
        detail:
          title: Detail
          description: Extra informatie bij de fout, indien beschikbaar
          type: string
          minLength: 1
        instance:
          title: Instance
          description: URI met referentie naar dit specifiek voorkomen van de fout.
            Deze kan gebruikt worden in combinatie met server logs, bijvoorbeeld.
          type: string
          minLength: 1
        invalidParams:
          type: array
          items:
            $ref: '#/components/schemas/FieldValidationError'
